#!/bin/bash

type _comp_filter &> /dev/null || return
type _comp_contains &> /dev/null || return
type _comp_filter_shorts &> /dev/null || return

function _tricot() {

    local cur prev opts

    _init_completion || return
    COMPREPLY=()

    # No completion
	if _comp_contains "--exclude --numbers --testers -p --positionals --variables" $prev; then
		return 0

    # Complete template modes
	elif _comp_contains "--template" $prev; then
        opts="plugin tester validator"

    # Options with filename completions
	elif _comp_contains "--plugins --validators --logfile" $prev; then
        _filedir
        return 0

	# Current wort starts with -*
    elif [[ "$cur" == -* ]]; then
		opts="--help"
		opts="$opts --debug"
		opts="$opts --exclude"
		opts="$opts --logfile"
		opts="$opts --numbers"
		opts="$opts --plugins"
		opts="$opts --positionals"
		opts="$opts --quite"
		opts="$opts --template"
		opts="$opts --testers"
		opts="$opts --validators"
		opts="$opts --variables"
		opts="$opts --verbose"

    # Default to filename completion
    else
        _filedir
        return 0
    fi

    _comp_filter "opts"
    _comp_filter_shorts "opts"

	mapfile -t COMPREPLY < <(compgen -W "${opts}" -- "${cur}") 
	return 0
}

complete -F _tricot tricot
